services:
  db:
    build:
      context: ./db
    container_name: tienda-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
      MYSQL_USER: tienda_user
      MYSQL_PASSWORD: tienda_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tienda-net

  backend:
    build:
      context: ./backend
    container_name: tienda-backend
    restart: unless-stopped
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: tienda_user
      DB_PASSWORD: tienda_pass
      DB_NAME: tienda_perritos
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - tienda-net

  frontend:
    build:
      context: ./frontend
    container_name: tienda-frontend
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - tienda-net

volumes:
  db_data:

networks:
  tienda-net:
    driver: bridge
