name: CI/CD Tienda Perritos - Backend

on:
  push:
    branches: ["deploy"]
    paths:
      - "backend/**"
      - ".github/workflows/cicd-tienda-backend.yml"

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Backend y push a ECR
        env:
          ECR_REPO: ${{ secrets.ECR_REPO_URL_BACKEND }}
        run: |
          cd backend
          docker build -t tienda-backend .
          docker tag tienda-backend:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest

      - name: Desplegar Backend via SSM
        env:
          ECR_REPO: ${{ secrets.ECR_REPO_URL_BACKEND }}
          ECR_REG: ${{ secrets.ECR_REGISTRY }}
          REGION: ${{ secrets.AWS_REGION }}
          INSTANCE: ${{ secrets.EC2_BACKEND_INSTANCE_ID }}
          DB_HOST: 172.31.26.221
        run: |
          aws ssm send-command \
            --instance-ids "$INSTANCE" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              \"aws ecr get-login-password --region $REGION | sudo docker login --username AWS --password-stdin $ECR_REG\",
              \"sudo docker pull $ECR_REPO:latest\",
              \"sudo docker stop tienda-backend || true\",
              \"sudo docker rm tienda-backend || true\",
              \"sudo docker run -d --name tienda-backend --restart unless-stopped -p 3001:3001 -e PORT=3001 -e DB_HOST=$DB_HOST -e DB_PORT=3306 -e DB_USER=tienda_user -e DB_PASSWORD=tienda_pass -e DB_NAME=tienda_perritos $ECR_REPO:latest\"
            ]" \
            --output text
